mysql:
  host: "192.168.204.129"
  port: "3306"
  db_name: "douyin"
  username: "douyin"
  password: "123456"
  config: "charset=utf8mb4&parseTime=True&loc=Local"

hertz:
  host: "192.168.31.226"
  port: "8080"

jwt:
  signing-key: "bytedance"
  expires-time: "7d"
  buffer-time: "1d"
  issuer: "linzijie"

video:
  video_upload_path: "./upload/videos"
  cover_upload_path: "./upload/covers"
  video_play_url: "videos"
  cover_show_url: "covers"

redis:
  Host: "192.168.204.129"
  Port: "6379"
  Password: "123456"
  DB: 0

zap:
  level: info
  format: console
  prefix: "[bytedance-camp-douyin]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
